# Air Now API with WxData

In this example, we will demonstrate using WxData with the Air Now API by doing the following:

1) Downloading the latest Air Quality Observations Within A Bounding Box:
   
   i) PM2.5
   
   ii) Ozone

## Imports

In [1]:
from wxdata import air_now_observations

**IMPORTANT**

Air Now API uses an API KEY. It is good cyber security practice to save the API Key into a .txt file and read the API Key in from the file.

WxData allows users to easily do this, though they need to store 1 key per file. If the user wants to manage their API Keys their own way, they can read in the
key from the file and pass it in by setting `api_key=API_KEY` and set `read_in_key_from_path=False`. If `read_in_key_from_path=True` then `api_key={full_path_to_api_key_text_file}`.

In [2]:
pm25 = air_now_observations.get_current_data_bounding_box(api_key=r'C:\Users\drewi\tests\keys\air_now_api_key.txt',
                                                          western_bound=-124.205070,
                                                          eastern_bound=-114.5,
                                                          southern_bound=30.21,
                                                          northern_bound=36.54)

In [3]:
pm25

     Latitude   Longitude   Unit  PM25  AQI  Category                time
0   36.481870 -121.733330  UG/M3  17.5   67         2 2026-08-04 06:00:00
1   36.209038 -121.125986  UG/M3  20.5   72         2 2026-08-04 06:00:00
2   35.494556 -120.666203  UG/M3   9.6   52         2 2026-08-04 06:00:00
3   35.259473 -120.644493  UG/M3  12.5   57         2 2026-08-04 06:00:00
4   35.046760 -120.587770  UG/M3   5.9   33         1 2026-08-04 06:00:00
5   35.020790 -120.563890  UG/M3   8.5   47         1 2026-08-04 06:00:00
6   34.637798 -120.456703  UG/M3  10.4   53         2 2026-08-04 06:00:00
7   34.890667 -120.432844  UG/M3  11.3   55         2 2026-08-04 06:00:00
8   34.394240 -119.514720  UG/M3  11.8   56         2 2026-08-04 06:00:00
9   36.308150 -119.312900  UG/M3   9.7   52         2 2026-08-04 06:00:00
10  34.448060 -119.231300  UG/M3   9.7   52         2 2026-08-04 06:00:00
11  34.252390 -119.143180  UG/M3   8.8   49         1 2026-08-04 06:00:00
12  35.356615 -119.062613  UG/M3  12.1   57         2 2026-08-04 06:00:00
13  34.210170 -118.870510  UG/M3   7.5   42         1 2026-08-04 06:00:00
14  36.489399 -118.826897  UG/M3   8.0   44         1 2026-08-04 06:00:00
15  36.135800 -118.810800  UG/M3   8.4   47         1 2026-08-04 06:00:00
16  34.404280 -118.809980  UG/M3  12.3   57         2 2026-08-04 06:00:00
17  34.276320 -118.683690  UG/M3  15.2   62         2 2026-08-04 06:00:00
18  34.199200 -118.533100  UG/M3   7.8   43         1 2026-08-04 06:00:00
19  34.383300 -118.528300  UG/M3  12.8   58         2 2026-08-04 06:00:00
20  34.181977 -118.363036  UG/M3  11.7   56         2 2026-08-04 06:00:00
21  34.066429 -118.226755  UG/M3  11.4   55         2 2026-08-04 06:00:00
22  33.901400 -118.205000  UG/M3   9.4   52         2 2026-08-04 06:00:00
23  35.049440 -118.188930  UG/M3   6.8   38         1 2026-08-04 06:00:00
24  34.725400 -118.178600  UG/M3   5.9   33         1 2026-08-04 06:00:00
25  33.793713 -118.171019  UG/M3   9.9   52         2 2026-08-04 06:00:00
26  33.830586 -117.938509  UG/M3   9.9   52         2 2026-08-04 06:00:00
27  36.487800 -117.871000  UG/M3   4.3   24         1 2026-08-04 06:00:00
28  34.143900 -117.850800  UG/M3  15.5   63         2 2026-08-04 06:00:00
29  35.643000 -117.713880  UG/M3   1.5    8         1 2026-08-04 06:00:00
30  33.629991 -117.675875  UG/M3  12.7   58         2 2026-08-04 06:00:00
31  33.996387 -117.492500  UG/M3  16.4   65         2 2026-08-04 06:00:00
32  34.100132 -117.491982  UG/M3  15.2   62         2 2026-08-04 06:00:00
33  33.999449 -117.415831  UG/M3  15.7   63         2 2026-08-04 06:00:00
34  33.217026 -117.396156  UG/M3   9.3   51         2 2026-08-04 06:00:00
35  33.676535 -117.331027  UG/M3  14.7   61         2 2026-08-04 06:00:00
36  34.510955 -117.325550  UG/M3   8.0   44         1 2026-08-04 06:00:00
37  32.710177 -117.142665  UG/M3  12.9   58         2 2026-08-04 06:00:00
38  32.845467 -117.123894  UG/M3  12.6   58         2 2026-08-04 06:00:00
39  33.447867 -117.088649  UG/M3   9.7   52         2 2026-08-04 06:00:00
40  32.985442 -117.082180  UG/M3  10.3   53         2 2026-08-04 06:00:00
41  33.583099 -117.072197  UG/M3  17.0   66         2 2026-08-04 06:00:00
42  32.631229 -117.059074  UG/M3  12.0   56         2 2026-08-04 06:00:00
43  32.552794 -117.047286  UG/M3  13.7   60         2 2026-08-04 06:00:00
44  32.789561 -116.944222  UG/M3  11.8   56         2 2026-08-04 06:00:00
45  32.579361 -116.929486  UG/M3  11.6   56         2 2026-08-04 06:00:00
46  34.264706 -116.861653  UG/M3   0.0    0         1 2026-08-04 06:00:00
47  33.920758 -116.858419  UG/M3  10.1   53         2 2026-08-04 06:00:00
48  33.944600 -116.830300  UG/M3   8.7   48         1 2026-08-04 06:00:00
49  32.842297 -116.768326  UG/M3  11.2   55         2 2026-08-04 06:00:00
50  33.725370 -116.206840  UG/M3  16.2   64         2 2026-08-04 06:00:00
51  33.719690 -116.189700  UG/M3  11.4   55         2 2026-08-04 06:00:00
52  33.379110 -116.016056  UG/M3   7.7   43         1 2026-08-04 06:00:00
53  32.791700 -115.561700  UG/M3   8.4   47         1 2026-08-04 06:00:00
54  32.978298 -115.538300  UG/M3   5.6   31         1 2026-08-04 06:00:00

In [4]:
o3 = air_now_observations.get_current_data_bounding_box(api_key=r'C:\Users\drewi\tests\keys\air_now_api_key.txt',
                                                          western_bound=-124.205070,
                                                          eastern_bound=-114.5,
                                                          southern_bound=30.21,
                                                          northern_bound=36.54,
                                                          parameter='ozone')

In [5]:
o3

     Latitude   Longitude Unit  OZONE  AQI  Category                time
0   36.481870 -121.733330  PPB     16   15         1 2026-08-04 05:00:00
1   36.485001 -121.155602  PPB     26   24         1 2026-08-04 05:00:00
2   36.209038 -121.125986  PPB     18   17         1 2026-08-04 05:00:00
3   35.361589 -120.836819  PPB     23   21         1 2026-08-04 05:00:00
4   35.494556 -120.666203  PPB     24   22         1 2026-08-04 05:00:00
..        ...         ...  ...    ...  ...       ...                 ...
83  36.048705 -115.052942  PPB     50   46         1 2026-08-04 05:00:00
84  36.404889 -114.879880  PPB     31   29         1 2026-08-04 05:00:00
85  35.969848 -114.835007  PPB     52   48         1 2026-08-04 05:00:00
86  32.690277 -114.614441  PPB     34   31         1 2026-08-04 05:00:00
87  33.612350 -114.602090  PPB     27   25         1 2026-08-04 05:00:00

[88 rows x 7 columns]